name: Media3 FFmpeg Extension / Publish

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Checkout Media3
        uses: actions/checkout@v4
        with:
          repository: androidx/media
          ref: release
          path: media

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
  
      # - name: Set up Gradle
      #   uses: gradle/gradle-build-action@v2
      
   
      # Set up NDK
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23c
          local-cache: false
          add-to-path: true
    
      # Build 
      - name: Build
        continue-on-error: false
        env:
          ANDROID_NDK_HOME: ${{steps.setup-ndk.outputs.ndk-path }}
          NDK_PATH: ${{ steps.setup-ndk.outputs.ndk-path }}
          ROOT_DIR:  ${{ github.workspace }}
        run: |
         echo "build ffmpeg"
         source ${{ github.workspace }}/.github/scripts/build.sh
         
         echo "Build Success"
        

      # Runs a set of commands using the runners shell
      - name: Upload FFmpeg Static Libs
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: "ffmpeg"
          path: ${{ github.workspace }}/media/libraries/decoder_ffmpeg/src/main/jni/ffmpeg/android-libs

      - name: Upload library
        continue-on-error: true
        uses: actions/upload-artifact@v3
        with:
          name: aar-library
          path: repo